version: "3"
services:
  proxy:
    build:
      context: ./proxy
    container_name: "${PROXY}"
    ports:
      - "${PROXY_PORT}:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/log:/var/log/nginx
    restart: "unless-stopped"
    depends_on:
      - express

  express:
    build:
      context: ./server
    container_name: "${EXPRESS}"
    expose:
      - "${EXPRESS_PORT}"
    restart: "unless-stopped"
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    container_name: "${MONGO}"
    volumes:
      - ./mongo/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
#    command:
 #     - mongod --dbpath /data/db

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    container_name: "${MONGO_EXPRESS}"
    ports:
      - "${MONGO_EXPRESS_PORT}:8081" # expose to onl myip in ec2 inbound rule
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_USERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_PASSWORD}"
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_USERNAME}:example@mongo:27017/" # password does not work
