version: "3"
services:
  proxy:
    build:
      context: ./proxy
    container_name: "${PROXY}"
    ports:
      - "${PROXY_PORT}:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/log:/var/log/nginx
    restart: "unless-stopped"
    depends_on:
      - express

  express:
    build:
      context: ./server
    container_name: "${EXPRESS}"
    expose:
      - "${EXPRESS_PORT}"
    restart: "unless-stopped"
