version: "3"
services:
  proxy:
    build:
      context: ./proxy
    container_name: proxy
    ports:
      - "16610:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/log:/var/log/nginx
    restart: "unless-stopped"
  express:
    build:
      context: ./server
    container_name: express
    expose:
      - "16620"
    restart: "unless-stopped"
